name: CI

on: [push]

jobs:
  test_and_docs:
    runs-on: ubuntu-latest
    env:
      LISP: sbcl
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkout Codex
        uses: actions/checkout@v2
        with:
          repository: shamazmazum/codex
          path: ~/lisp/codex
      - name: Checkout docparser
        uses: actions/checkout@v2
        with:
          repository: shamazmazum/docparser
          path: ~/lisp/docparser
      - name: Install dependencies
        run: |
          sudo apt-get install info install-info
      - name: Install CIM
        run: |
          curl -L https://raw.githubusercontent.com/shamazmazum/cl-cirrus/github-actions/install-actions.sh | sh
      - name: Build documentation
        run: |
          cl -l cl-value-noise/doc -e '(cl-value-noise-doc:build-manual)'
      - name: Deploy to GH pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/cl-value-noise/html
